include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

phpunit:
  extends: .phpunit-base
  services:
    - !reference [.with-database]
    - !reference [.with-chrome]
    - !reference [.with-chrome-legacy]
    - name: collabora/code:latest
      entrypoint: ["sh"]
      alias: 'collabora.test'
      variables:
        username: admin
        password: admin
        extra_params: |
          --o:ssl.enable=false
          --o:storage.wopi.alias_groups[@mode]=groups
          --o:storage.wopi.alias_groups.group[0].host=$DTT_BASE_URL
          --o:storage.wopi.alias_groups.group[0].host[@allow]=true
      command:
        - -c
        # Manually generate the proof key, replicating the behavior of "coolconfig generate-proof-key".
        # The coolconfig command can produce inconsistent results, as the service occasionally interrupts execution.
        - |
          openssl genpkey -algorithm RSA -out /etc/coolwsd/proof_key -pkeyopt rsa_keygen_bits:2048 &&
          openssl rsa -in /etc/coolwsd/proof_key -outform PEM -pubout -out /etc/coolwsd/proof_key.pub &&
          /start-collabora-online.sh
  before_script:
    - !reference [.setup-webserver]
    - !reference [.simpletest-db]
    - drush -y site-install minimal --db-url=mysql://$MYSQL_USER:$MYSQL_PASSWORD@database/$MYSQL_DATABASE
    - drush -y pm:install collabora_online
    - drush -y config-set collabora_online.settings cool.wopi_base $DTT_BASE_URL
    - drush -y config-set collabora_online.settings cool.server http://collabora.test:9980/
    - drush -y config-set collabora_online.settings cool.key_id collabora
    - drush -y config-set collabora_online.settings cool.disable_cert_check 1
    - drush -y config-set media.settings standalone_url 1
    - echo '$settings["extension_discovery_scan_tests"] = TRUE;' >> $CI_PROJECT_DIR/$_WEB_ROOT/sites/default/settings.php
    - drush -y pm:install collabora_online_test
    - drush -y pm:uninstall collabora_online_test
    - rm /var/www/html/web # Remove symlink to allow .setup-webserver to be re-executed.
  script:
    - curl http://collabora.test:9980/hosting/capabilities | json_pp
    - !reference [.phpunit-base, script]

variables:
  DTT_BASE_URL: $SIMPLETEST_BASE_URL
  DTT_MINK_DRIVER_ARGS: $MINK_DRIVER_ARGS_WEBDRIVER_DEFAULT
  _SHOW_ENVIRONMENT_VARIABLES: '1'
  OPT_IN_TEST_PREVIOUS_MAJOR: '1'
