version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:8.3
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - ../collabora-drupal:/var/www/collabora-drupal
      # - $HOME/.composer/.auth.json:$HOME/.composer/.auth.json
    environment:
      DOCUMENT_ROOT: /var/www/html/web
      # By leaving these variables empty Docker Compose will set them to their host values.
      # XDEBUG CONFIGURATION.
      XDEBUG_CONFIG: "client_host=172.17.0.1" # Non-Mac users.
      # XDEBUG_CONFIG: "client_host=host.docker.internal" # Mac users.
      XDEBUG_MODE: "develop, debug"
      PHP_IDE_CONFIG: "serverName=Docker"
      # Enable step debugging for all PHP request. See ./README.md#step-debugging for more information.
      # XDEBUG_SESSION: 1
    networks:
      default:
        aliases:
          - "web.test"

  mysql:
    image: percona/percona-server:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql

  selenium:
    image: selenium/standalone-chrome:4.1.3-20220405
    environment:
      - DISPLAY=:99
      - VNC_NO_PASSWORD=1
    ports:
      - '7900:7900'

  collabora:
    image: collabora/code
    ports:
      - '9980:9980'
    networks:
      default:
        aliases:
          - "collabora.test"
    environment:
      username: admin
      password: admin
      extra_params: "\
        --o:ssl.enable=false \
        --o:storage.wopi.alias_groups[@mode]=groups \
        --o:storage.wopi.alias_groups.group[0].host=http://web.test \
        --o:storage.wopi.alias_groups.group[0].host[@allow]=true \
        --o:storage.wopi.alias_groups.group[0].alias[0]=http://localhost"
    # Manually generate the proof key, replicating the behavior of "coolconfig generate-proof-key".
    command:
      - sh
      - -c
      - >
        openssl genpkey -algorithm RSA -out /etc/coolwsd/proof_key -pkeyopt rsa_keygen_bits:2048 &&
        openssl rsa -in /etc/coolwsd/proof_key -outform PEM -pubout -out /etc/coolwsd/proof_key.pub &&
        /start-collabora-online.sh

volumes:
  mysql: # eslint-disable-line yml/no-empty-mapping-value
