collabora_online.settings:
  type: config_object
  label: 'Settings'
  mapping:
    cool:
      type: config_object
      label: 'Cool'
      mapping:
        server:
          type: uri
          label: 'The address of the COOL server.'
        discovery_cache_ttl:
          type: integer
          label: 'Discovery cache TTL'
          constraints:
            Range:
              min: 0
        wopi_base:
          type: uri
          label: 'The WOPI base'
        key_id:
          type: string
          label: 'The JWT key id'
        access_token_ttl:
          type: integer
          label: 'Access Token TTL'
        disable_cert_check:
          type: boolean
          label: 'Disable cert checks.'
        wopi_proof:
          type: boolean
          label: 'Verify WOPI proof header and timestamp.'
        allowfullscreen:
          type: boolean
          label: 'Allow full-screen.'
        new_file_interval:
          type: integer
          label: 'New file interval.'

key.type.collabora_jwt_hs:
  # The key type has no actual configurable settings, but it still needs a
  # configuration schema.
  type: sequence

field.formatter.settings.collabora_preview_iframe:
  type: mapping
  label: 'Collabora Online preview iframe formatter settings'
  mapping:
    aspect_ratio:
      type: string
      label: 'Iframe aspect ratio'
      constraints:
        Regex:
          pattern: '#^[1-9]\d* / [1-9]\d*$#'
          message: "Please provide two numbers, separated by ' / '."

views.field.media_collabora_preview:
  type: views_field
  label: 'Collabora view link'
  mapping:
    text:
      type: label
      label: 'Text to display'

views.field.media_collabora_edit:
  type: views.field.media_collabora_preview
  label: 'Collabora edit link'
